# Generated by Django 3.1.7 on 2021-04-02 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20210402_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/subCategories/2021-04-02 22:48:27.804846'),
        ),
        migrations.AlterField(
            model_name='product',
            name='s_categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/subCategories/2021-04-02 22:48:27.805751'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='m_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s_cat', to='shop.maincategory'),
        ),
    ]
